### ISSUE TITLE
CSS固定宽高比

### ISSUE THREAD

**Issue by xieww** [xieww/magic-warehouse#6]
* 如果元素的尺寸已知的话，计算好宽高写上去就行了。
* 如果元素尺寸未知，最简单的方法是用 JavaScript 实现，如果用 CSS 的话又要分为以下几种：
     * 如果是可替换元素<img>或<video>，可以将width/height其一设定尺寸，另一个设为auto，则可替换元素会根据其固有尺寸进行变化。
     * 如果是普通的元素，
       * 可以通过padding-top/padding-bottom的方式来模拟固定宽高比，不过这种方式不灵活，只能够高度随着宽度变。
       * CSS新特性aspect-ratio，可以很方便地指定宽高比。

### img

```css
.box{
   width: 30vw;
   margin: 10px auto;
   padding: 10px;
   border: 1px solid #000;
   font-size: 0;
}

img {
   width: 100%;
   height: auto;
}

<div class="box">
  <img src="./background.png" alt="">
</div>
```

### padding-top/padding-bottom
```css
.box {
   width: 50%;
   height: 0;
   padding-bottom: 30%; /*宽高比为5:3*/
   background-color: aqua;
}

<div class="box">CSS</div>
```
      
### aspect-ratio
```css
/* 高度随动 */
.box1 {
    width: 50%;
    height: auto;
    aspect-ratio: 16/9;
}

/* 宽度随动 */
.box2 {
    height: 50%;
    width: auto;
    aspect-ratio: 16/9;
 }

<div class="box1">CSS</div>
<div class="box2">CSS</div>

```
